apiVersion: v1
kind: Pod
metadata:
  name: pod-storage
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: storage
      mountPath: /test1
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: pvc-claim-2
